name: Android CI

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Generate Keystore
      run: |
        keytool -genkeypair -v \
          -keystore app/hanwoo.jks \
          -alias hanwoo-alias \
          -keyalg RSA \
          -keysize 2048 \
          -validity 10000 \
          -storepass "mnplimc!00$" \
          -keypass "mnplimc!00$" \
          -dname "CN=MNPLimc, OU=IT, O=MNPLimc, L=Seoul, S=Seoul, C=KR"

    - name: Download Gradle Wrapper
      run: gradle wrapper --gradle-version 8.2

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Build APK & AAB (Release)
      run: ./gradlew assembleRelease bundleRelease

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: hanwoo-apk
        path: app/build/outputs/apk/release/app-release.apk

    - name: Upload AAB
      uses: actions/upload-artifact@v4
      with:
        name: hanwoo-aab
        path: app/build/outputs/bundle/release/app-release.aab
